name: Semgrep Code Scan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep with Custom Rules
        run: |
          semgrep --config rule.yaml --json --json-output /tmp/semgrep.json
      - name: View the output
        run: cat /tmp/semgrep.json
