on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/SAST.yml
name: SAST comparison
jobs:
  semgrep-free:
    name: Semgrep-free
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: |
        semgrep scan --json --json-output /tmp/semgrep.json
    - name: View the output
      run: cat /tmp/semgrep.json
