name: Semgrep Finding

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml

jobs:
  semgrep-free:
    name: Semgrep Free Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Semgrep scan in SARIF format
      - name: Run Semgrep scan
        run: |
          semgrep scan --sarif --output /tmp/semgrep.sarif

      # Step 3: View the Semgrep output in logs
      - name: View the output
        run: cat /tmp/semgrep.sarif

      # Step 4: Upload the Semgrep SARIF output as an artifact
      - name: Upload Semgrep SARIF output
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sarif-output
          path: /tmp/semgrep.sarif
